/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.spl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FeatureMapStandaloneSetup extends FeatureMapStandaloneSetupGenerated {

	public static void doSetup() {
		new FeatureMapStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
