/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.spl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FeatureMapRuntimeModule extends AbstractFeatureMapRuntimeModule {
}
