/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.spl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.tubs.skeditor.spl.FeatureMapRuntimeModule;
import de.tubs.skeditor.spl.FeatureMapStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FeatureMapIdeSetup extends FeatureMapStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FeatureMapRuntimeModule(), new FeatureMapIdeModule()));
	}
	
}
