/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.spl.ide;


/**
 * Use this class to register ide components.
 */
public class FeatureMapIdeModule extends AbstractFeatureMapIdeModule {
}
