/*
 * generated by Xtext 2.22.0
 */
package de.tubs.skeditor.spl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FeatureMapUiModule extends AbstractFeatureMapUiModule {

	public FeatureMapUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
